import { mockCaseDoc, flattenDocText } from '../__fixtures__/case-doc.fixture';
import { cheklistTemplate } from './cheklist';

describe('cheklistTemplate', () => {
  it('renders a valid def containing the required dossier + notary document names', () => {
    const c = mockCaseDoc();
    const def = cheklistTemplate(c);
    const text = flattenDocText(def);

    expect(def.content).toBeDefined();
    expect(text).toContain('Шартнома');
    expect(text).toContain('Гаров шартномаси');
  });

  it('marks system-generated documents present and matches uploaded documents by heuristic', () => {
    const c = mockCaseDoc();
    const text = flattenDocText(cheklistTemplate(c));

    // Generated by this same PDF pipeline — always shown present.
    expect(text).toContain('☑ (тизимда)');
    // The fixture includes an uploaded "КАТМ ҳисоботи" and a "Гаров шартномаси" NOTARY doc.
    expect(text).toContain('☑');
  });

  it('shows an unchecked box for a required document that has not been uploaded', () => {
    const c = mockCaseDoc({ documents: [] });
    const text = flattenDocText(cheklistTemplate(c));

    expect(text).toContain('☐');
  });
});
