import type { TDocumentDefinitions, TableCell } from 'pdfmake/interfaces';
import { CaseDocData } from '../case-document.loader';
import { orgHeader, docTitle, gridTable } from '../doc-layout';

type CaseDocument = CaseDocData['documents'][number];

interface ChecklistItem {
  name: string;
  /** Produced by this same PDF-generation pipeline — always present once the dossier is assembled. */
  generated?: boolean;
  /** Heuristic match against an uploaded/scanned entry in `c.documents` (by type/title). */
  match?: (d: CaseDocument) => boolean;
}

/** Main dossier documents, in filing order. */
const DOSSIER_ITEMS: ChecklistItem[] = [
  { name: 'Мурожаатнома', generated: true },
  { name: 'Бош келишув (РКЛ Ген)', generated: true },
  { name: 'Скоринг таҳлил', generated: true },
  { name: 'Акт согласования', generated: true },
  { name: 'Приказ', generated: true },
  { name: 'Шартнома', generated: true },
  { name: 'КАТМ ҳисоботи', match: (d) => /катм/i.test(d.title ?? d.fileName ?? '') },
  { name: 'Тўлов жадвали (график)', match: (d) => /жадвал|график/i.test(d.title ?? d.fileName ?? '') },
  { name: 'Обложка', generated: true },
  { name: 'Далолатнома', match: (d) => /далолат/i.test(d.title ?? '') },
  { name: 'Чек-лист', generated: true },
  { name: 'Пул ўтказиш аризаси', match: (d) => /пул\s*ўтказиш/i.test(d.title ?? d.fileName ?? '') },
];

/** Notarius orqali rasmiylashtiriladigan hujjatlar. */
const NOTARY_ITEMS: ChecklistItem[] = [
  { name: 'Гаров шартномаси', match: (d) => d.type === 'NOTARY' && /гаров/i.test(d.title ?? '') },
  { name: 'Тақиқ карточкаси', match: (d) => d.type === 'NOTARY' && /тақиқ/i.test(d.title ?? '') },
  { name: 'Умумий иш (Опшая дела)', match: (d) => d.type === 'OTHER' && /умумий|опшая/i.test(d.title ?? '') },
];

function statusText(item: ChecklistItem, docs: CaseDocument[]): string {
  if (item.generated) return '☑ (тизимда)';
  return item.match && docs.some(item.match) ? '☑' : '☐';
}

function tableRows(items: ChecklistItem[], docs: CaseDocument[], startNo: number): TableCell[][] {
  return items.map((item, i) => [
    { text: String(startNo + i), alignment: 'center' },
    { text: item.name },
    { text: statusText(item, docs), alignment: 'center' },
  ]);
}

const HEADER_ROW: TableCell[] = [
  { text: '№', bold: true, alignment: 'center' },
  { text: 'Ҳужжат номи', bold: true },
  { text: 'Ҳолати', bold: true, alignment: 'center' },
];

/**
 * Чек-лист — the required-document checklist for the dossier. Documents generated by this same
 * PDF pipeline are always shown present; uploaded/notarized documents are matched heuristically
 * against `c.documents`.
 */
export function cheklistTemplate(c: CaseDocData): TDocumentDefinitions {
  const docs = c.documents ?? [];
  const contractNo = c.contractNumber ?? c.number ?? '—';

  return {
    defaultStyle: { font: 'Roboto', fontSize: 10 },
    pageMargins: [45, 50, 45, 50],
    content: [
      orgHeader(c.organization),
      docTitle('ҲУЖЖАТЛАР РЎЙХАТИ (ЧЕК-ЛИСТ)', `Иш № ${contractNo}`),
      {
        table: { widths: [24, '*', 90], body: [HEADER_ROW, ...tableRows(DOSSIER_ITEMS, docs, 1)] },
        layout: gridTable,
        margin: [0, 2, 0, 10],
      },
      { text: 'Нотариал ҳужжатлар:', bold: true, margin: [0, 0, 0, 6] },
      {
        table: { widths: [24, '*', 90], body: [HEADER_ROW, ...tableRows(NOTARY_ITEMS, docs, DOSSIER_ITEMS.length + 1)] },
        layout: gridTable,
        margin: [0, 2, 0, 4],
      },
    ],
  };
}
